### ISSUE TITLE
Bootstrap with this data

### ISSUE THREAD

**Issue by pwalsh** [opentrials/interventions#1]
Drug database assessment doc: https://docs.google.com/document/d/10N1re-bza0V-Om00OyLsw7jgzSqIl5ijRU23idJOjZI/edit#heading=h.whkiou3kp0xb

**Comment by pwalsh** [comment]
Hey @danfowler just close this when you are done.

**Comment by danfowler** [comment]
Closed by https://github.com/opentrials/interventions/commit/f9cc1512fe1188032c757b148643326204a88126
